### ISSUE TITLE
race.py file too big to be displayed by github

### ISSUE THREAD

**Issue by selik** [adamdeprince/demographics#1]
https://github.com/adamdeprince/demographics/blob/master/demographics/data/us/race.py

Gives an error message instead of displaying the source code.

**Comment by adamdeprince** [comment]
Yeah, this file was machine generated.   The data -> code compiler optimizes for python load speed, minimal python file size and maximal opportunities to intern and reuse immutable data types like tuples that are not ordinarily auto interned by the interpreter.     Being visible on github wasn't a design criteria.
